export const MAIN__GET_DATA = 'MAIN__GET_DATA';
export const MAIN__SET_DATA = 'MAIN__SET_DATA';

export const MAIN__GET_SELECT_OBJECT = 'MAIN__GET_SELECT_OBJECT';
export const MAIN__SET_SELECT_OBJECT = 'MAIN__SET_SELECT_OBJECT';

